"""Turn a page saved from Office Ally into a clean, shareable TEMPLATE for the extension's tests.

A page saved from a logged-in Office Ally session is not a template: it also carries the login
username, the practice's company id, the patient's name / date of birth / chart history, and session
state. Those must never be committed. This keeps ONLY what the Cadence extension reads — by
allowlist, not by trying to scrub everything else:

  * every SOAP note box (<textarea id="…ucSOAPNote_X">), emptied, with its limit and its hidden
    "_Label" field (the practice's name for the box)
  * the SOAP Note Layout dropdown (layout ids and names)
  * the Encounter Date boxes, the encounter id and the page title — with FAKE values
  * the Patient ID — FAKE
  * one Apply button

and then refuses to write the file if any real identifier from the source page is still in it.

    .venv/Scripts/python.exe scripts/make_oa_template.py evals/Ingestion/OfficeAlly_Initial_Eval.html \\
        extension/tests/fixtures/oa_cadence_init_eval.html
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

FAKE_PID = "100000001"
FAKE_EID = "900000001"
FAKE_DATE = ("9", "28", "2026")
P = "ctl00_phFolderContent_ucSOAPNote_"


def _first(pattern: str, text: str, flags=re.S | re.I) -> str:
    m = re.search(pattern, text, flags)
    if not m:
        return ""
    return m.group(1) if m.groups() else m.group(0)


def build(src: str) -> tuple[str, list[str]]:
    real_pid = _first(r'id="ctl00_phFolderContent_myPatientHeader_lblPatientID"[^>]*>(\d+)', src) \
        or _first(r"[?&](?:amp;)?PID=(\d+)", src)
    real_eid = _first(r'id="' + P + r'EncounterID" value="(\d+)"', src)
    dob = _first(r'myPatientHeader_PatientDOB" value="([^"]+)"', src)
    title = _first(r'id="' + P + r'lblTitle"[^>]*>([^<]*)', src)
    title = re.sub(r"Encounter ID \d+", "Encounter ID " + FAKE_EID, html.unescape(title)).strip() or "Add Note / Encounter"

    parts = []
    # Note boxes in page order, each with its label field and a visible header (the label).
    for m in re.finditer(r'<textarea\b[^>]*\bid="' + P + r'([SOAP]_[A-Za-z0-9_]+)"[^>]*>.*?</textarea>', src, re.S | re.I):
        key = m.group(1)
        open_tag = re.match(r"<textarea\b[^>]*>", m.group(0), re.I).group(0)
        label_in = _first(r'<input type="hidden"[^>]*id="' + P + re.escape(key) + r'_Label"[^>]*>', src)
        label = html.unescape(_first(r'value="([^"]*)"', label_in)) if label_in else ""
        parts.append('<div class="soap-box"><div class="hdr">' + html.escape(label or key) + "</div>\n"
                     + (label_in + "\n" if label_in else "") + open_tag + "</textarea></div>")
    layout = _first(r'<select[^>]*id="' + P + r'ddlSoapLayout".*?</select>', src)
    date_inputs = []
    for part, val in zip(("Month", "Day", "Year"), FAKE_DATE):
        tag = _first(r'<input[^>]*id="' + P + r'EncounterDate_' + part + r'"[^>]*>', src)
        date_inputs.append(re.sub(r'value="[^"]*"', 'value="' + val + '"', tag))

    page = (
        "<!doctype html>\n<html><head><meta charset=\"utf-8\"><title>Office Ally note form (template)</title></head><body>\n"
        "<!-- Generated by scripts/make_oa_template.py from a saved Office Ally page. Structure only: no\n"
        "     patient, practice, user or session data. IDs and dates are fake. -->\n"
        '<form name="aspnetForm" method="post" id="aspnetForm">\n'
        '<div>Patient ID: <span id="ctl00_phFolderContent_myPatientHeader_lblPatientID" class="data_new">' + FAKE_PID + "</span></div>\n"
        '<span id="' + P + 'lblTitle" class="BannerTitleText">' + html.escape(title) + "</span>\n"
        '<input type="hidden" name="ctl00$phFolderContent$ucSOAPNote$EncounterID" id="' + P + 'EncounterID" value="' + FAKE_EID + '" />\n'
        "<div>Encounter Date: " + " / ".join(date_inputs) + "</div>\n"
        "<div>SOAP Note Layout: " + layout + "</div>\n"
        + "\n".join(parts) + "\n"
        '<input id="Button10" class="button" onclick="Apply_Click()" type="button" value="Apply" name="btnApplyChange" />\n'
        "</form>\n</body></html>\n"
    )
    leaks = []
    for name, value in (("patient id", real_pid), ("encounter id", real_eid), ("date of birth", dob)):
        if value and value in page:
            leaks.append(name)
    for word in ("sdmobilept", "1173855", "companyid", "__viewstate", "token", "kushang", "desai"):
        if word in page.lower():
            leaks.append(word)
    return page, leaks


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2
    src = Path(argv[1]).read_text(encoding="utf-8", errors="replace")
    page, leaks = build(src)
    if leaks:
        print("REFUSED: the template would still contain: " + ", ".join(sorted(set(leaks))))
        return 1
    out = Path(argv[2])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page, encoding="utf-8")
    boxes = page.count("<textarea")
    print(f"wrote {out} ({boxes} note boxes, {len(page):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
